"""delete on cascade for issues_tags

Revision ID: 0bea779c5e23
Revises: ea54e44c5bee
Create Date: 2025-08-02 17:45:09.454316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bea779c5e23'
down_revision = 'ea54e44c5bee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues_tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('issues_tags_issue_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('issues_tags_tag_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'issues', ['issue_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('issues_tags_tag_id_fkey'), 'tags', ['tag_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('issues_tags_issue_id_fkey'), 'issues', ['issue_id'], ['id'])

    # ### end Alembic commands ###
