"""fix display_order nullable and add defaults

Revision ID: 3645c335dd8d
Revises: e16204a278d2
Create Date: 2025-08-02 17:03:53.950031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3645c335dd8d'
down_revision = 'e16204a278d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.alter_column('display_order',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
