"""Add author column to issues

Revision ID: d836aba385ef
Revises: 
Create Date: 2025-07-24 18:48:59.939974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd836aba385ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_sync')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('author')

    op.create_table('test_sync',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_sync_pkey'))
    )
    # ### end Alembic commands ###
