"""add display_order to priorities, statuses, tags

Revision ID: e16204a278d2
Revises: 3f6286ad1d20
Create Date: 2025-08-02 16:53:18.455484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16204a278d2'
down_revision = '3f6286ad1d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
