"""add cascade deletes remove assignee enforce unique tags

Revision ID: ea54e44c5bee
Revises: 3645c335dd8d
Create Date: 2025-08-02 17:35:57.262382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea54e44c5bee'
down_revision = '3645c335dd8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('comments_issue_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('comments_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'issues', ['issue_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('issues_assignee_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('issues_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('assignee_id')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('issues_author_id_fkey'), 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('issues_assignee_id_fkey'), 'users', ['assignee_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('comments_author_id_fkey'), 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('comments_issue_id_fkey'), 'issues', ['issue_id'], ['id'])

    # ### end Alembic commands ###
