"""Add password_hash and role to User

Revision ID: ff2d89cb14b5
Revises: d836aba385ef
Create Date: 2025-07-25 18:07:10.595863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2d89cb14b5'
down_revision = 'd836aba385ef'
branch_labels = None
depends_on = None


def upgrade():
    # Add password_hash with a temporary server default (blank string)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    # Remove the server default for password_hash and role
    op.alter_column('users', 'password_hash', server_default=None)
    op.alter_column('users', 'role', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
